# Alacritty Configuration
[font]
size = 7

[cursor]
style = {shape = 'Block',blinking = 'On'}
thickness = 1.0

[mouse]
hide_when_typing = true

[window]
decorations = 'Full'
padding = { x = 0, y = 0 }
