# Alacritty Configuration
[shell]
program = '/bin/bash'

[font]
normal = { family = 'OpenDyslexicM Nerd Font Propo', style = 'Regular' }
bold = { family = 'OpenDyslexicM Nerd Font Propo', style = 'Regular' }
italic = { family = 'OpenDyslexicM Nerd Font Propo', style = 'Regular' }
bold_italic = { family = 'OpenDyslexicM Nerd Font Propo', style = 'Regular' }
size = 7

[cursor]
style = {shape = 'Block',blinking = 'On'}
thickness = 1

[mouse]
hide_when_typing = true

[window]
opacity = 0.9
