#!/bin/bash
#.dotfiles/install
# Gabriel Góes Rocha de Lima
# 2013-04-# Modificado de ThePrimeagen/.dotfiles
#
# Descrição : Script de definição de variáveis para stow
#
if [[ -z $CONFIG_FOLDERS ]]; then
    CONFIG_FOLDERS="alacritty i3 nvim picom tmux"
fi

if [[ -z $BASHRC ]]; then
    BASHRC=".bashrc .bash_profile .bash_aliases .bash_path .bash_prompt"
fi

if [[ -z $SCRIPTS ]]; then
    SCRIPTS='Postgre'
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

CONFIG_FOLDERS=$CONFIG_FOLDERS BASHRC=$BASHRC SCRIPTS=$SCRIPTS DOTFILES=$DOTFILES $DOTFILES/install

