#!/bin/bash
#.dotfiles/arch
# Gabriel Góes Rocha de Lima
# 2013-04-# Modificado de ThePrimeagen/.dotfiles
#
# Descrição : Script de definição de variáveis para stow

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

if [[ -z $CONFIG_FOLDERS ]]; then
    CONFIG_FOLDERS="ipython fontconfig alacritty i3 nvim tmux xplr"
fi

CONFIG_FOLDERS=$CONFIG_FOLDERS DOTFILES=$DOTFILES $HOME/.dotfiles/install

