#!/bin/bash
# if qgis is runing, close it
if pgrep -x "qgis" > /dev/null
then
    echo "QGIS is running. Closing it..."
    pkill qgis
fi

rm -rf $HOME/.local/share/QGIS/QGIS3/profiles/Gabriel/python/plugins/mapgeo
cp -r $HOME/projetos/PreditorTerra/fonte/mapgeo $HOME/.local/share/QGIS/QGIS3/profiles/Gabriel/python/plugins

pushd $HOME
export PYTHONPATH=$HOME/.pyenv/versions/geologia/lib/python3.12/site-packages:$HOME/.pyenv/versions/geologia/bin/python:$PYTHONPATH

exec qgis &
popd

echo "Classificador Terra instalado com sucesso!"
