#!/bin/bash
# create a bash script to navigate to project directory
# open urxvt with tmux and execute geo alias
# Then, open nvim at the project directory
#
# Usage: ./test.sh
# Author: Gabriel Góes Rocha de Lima
# Date: 2024-01-31
# Version: 0.1
# Description: This script will open urxvt with tmux and execute geo alias
# Options: None

SESSION_NAME="󰇧PreditorTerra󰇧"
CLASS_NAME="󰇧PreditorTerra󰇧"
COMANDOS='vim .'

# Checa se existe sessão chamada $SESSION_NAME
if tmux has-session -t $SESSION_NAME 2>/dev/null; then
    # Se existir, verifica se está attached
    if ! tmux list-sessions -F "#{session_name}:#{session_attached}" | grep -q "^$SESSION_NAME:1$"; then
        # Se não estiver attached, attach à sessão
        alacritty --class $CLASS_NAME -e bash -c "tmux attach-session -t $SESSION_NAME"
    else
        # Se estiver attached, foca na janela com i3-wm
        # Pega o workspace da janela $CLASS_NAME
        WORKSPACE=$(i3-msg -t get_workspaces | jq '.[] | select(.name == "'$CLASS_NAME'") | .num')
        # Foca no workspace e na janela
        i3-msg workspace $WORKSPACE && i3-msg [class="$CLASS_NAME"] focus
    fi
else
    # Se não existir, cria uma nova sessão
    # Abre terminal com $CLASS_NAME com tmux $SESSION_NAME, executa $COMANDOS e attach à sessão
    alacritty -T $CLASS_NAME -e bash -c "tmux new-session -s $SESSION_NAME -d &&
        tmux send-keys -t $SESSION_NAME '$COMANDOS' C-m &&
        tmux attach-session -t $SESSION_NAME"
fi
